name: sam_conda
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - numpy
    - napari
    - scikit-image
    - torch
    - torchvision
    - git+https://github.com/facebookresearch/segment-anything.git